// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "full_name":
			out.FullName = string(in.String())
		case "birthday":
			out.Birthday = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "img_url":
			out.ImgUrl = string(in.String())
		case "subs":
			if in.IsNull() {
				in.Skip()
				out.Subs = nil
			} else {
				in.Delim('[')
				if out.Subs == nil {
					if !in.IsDelim(']') {
						out.Subs = make([]Subscription, 0, 8)
					} else {
						out.Subs = []Subscription{}
					}
				} else {
					out.Subs = (out.Subs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Subscription
					(v1).UnmarshalEasyJSON(in)
					out.Subs = append(out.Subs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"birthday\":"
		out.RawString(prefix)
		out.String(string(in.Birthday))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"img_url\":"
		out.RawString(prefix)
		out.String(string(in.ImgUrl))
	}
	{
		const prefix string = ",\"subs\":"
		out.RawString(prefix)
		if in.Subs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Subs {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity(l, v)
}
func easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity1(in *jlexer.Lexer, out *Subscription) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "employee_id":
			out.EmployeeId = uint32(in.Uint32())
		case "interval":
			out.Interval = uint16(in.Uint16())
		case "is_followed":
			out.IsFollowed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity1(out *jwriter.Writer, in Subscription) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"employee_id\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.EmployeeId))
	}
	{
		const prefix string = ",\"interval\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Interval))
	}
	{
		const prefix string = ",\"is_followed\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsFollowed))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Subscription) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Subscription) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity1(l, v)
}
func easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity2(in *jlexer.Lexer, out *ResponseDetail) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "detail":
			out.Detail = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity2(out *jwriter.Writer, in ResponseDetail) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"detail\":"
		out.RawString(prefix[1:])
		out.String(string(in.Detail))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseDetail) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseDetail) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity2(l, v)
}
func easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity3(in *jlexer.Lexer, out *ErrorDetail) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity3(out *jwriter.Writer, in ErrorDetail) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorDetail) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeGithubComCantylvServiceHappyBirthdayInternalEntity3(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorDetail) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeGithubComCantylvServiceHappyBirthdayInternalEntity3(l, v)
}
