# Copyright © ivanlobanov. All rights reserved.
nginx:
  host: domain.ru
  port: 80

server:
  host: domain.ru
  port: 8000
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 1m

kafka:
  host: domain.ru
  port: 6473

mongodb:
  host: domain.ru
  port: 27017
  root: admin
  root_password: 123

memcache:
  host: domain.ru
  port: 11211

redis:
  host: domain.ru
  port: 6379
  root: admin
  root_password: 123
  max_connection_retries: 3
  min_retry_backoff: 10ms
  max_retry_backoff: 300ms
  dial_timeout: 5s

  