# Copyright © ivanlobanov. All rights reserved.
server:
  host: server
  port: 8000
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 1m

kafka:
  host: kafka
  port: 9092
  topic: emails

mongo:
  host: mongo
  port: 27017
  conn_name: server
  conn_pwd: server123

memcached:
  host: memcached
  port: 11211
  