# Copyright © ivanlobanov. All rights reserved.
nginx:
  host: 127.0.0.1
  port: 80

server:
  host: 127.0.0.1
  port: 8000
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 1m

kafka:
  host: 127.0.0.1
  port: 6473

mongodb:
  host: 127.0.0.1
  port: 27017
  root: admin
  root_password: 123

memcache:
  host: 127.0.0.1
  port: 11211
  